# fly.toml app configuration file generated for ssafy-ai-chat-back on 2024-12-31T15:31:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ssafy-ai-chat-back'
primary_region = 'nrt'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
